#!/usr/bin/env uv --script

# /// script
# dependencies = [
#   "pyyaml",
# ]
# ///

"""Synchronize publications data from the lab website's source of truth.

Fetches content/publications.yaml from the rendeirolab.github.io repository
(GitHub raw, main branch) and converts it into _data/publications.yml for
this Jekyll site. The lab YAML is the single source of truth for
publications; this file should not be edited by hand.
"""

import sys
import urllib.request
from pathlib import Path

import yaml

LAB_YAML_URL = (
    "https://raw.githubusercontent.com/rendeirolab/rendeirolab.github.io/"
    "main/content/publications.yaml"
)
AUTHOR_NAME = "André F. Rendeiro"

# Resource type -> bootstrap-icons icon class
RESOURCE_ICONS = {
    "PDF": "bi-file-earmark-pdf",
    "Preprint": "bi-file-earmark-richtext",
    "Data": "bi-database",
    "Code": "bi-github",
    "Notebook": "bi-journal-bookmark-fill",
    "Press": "bi-newspaper",
    "Video": "bi-camera-reels",
}


def fetch_lab_yaml() -> dict:
    with urllib.request.urlopen(LAB_YAML_URL) as response:
        return yaml.safe_load(response.read().decode("utf-8"))


def transform(publications: dict) -> list:
    entries = {}
    for section in ("publications", "previous_publications"):
        entries.update(publications[section])

    out: list = []
    for doi, pub in entries.items():
        pub_type = pub.get("type", "journal")
        if pub_type not in ("journal", "preprint", "opinion", "review"):
            print(f"WARNING: unknown publication type '{pub_type}' for {doi}, treated as journal", file=sys.stderr)
            pub_type = "journal"

        authors = pub["authors"].replace(AUTHOR_NAME, f"<u>{AUTHOR_NAME}</u>")
        resources = []
        for resource in pub.get("resources") or []:
            for resource_type, link in resource.items():
                resources.append(
                    {
                        "type": resource_type,
                        "link": link,
                        "icon": RESOURCE_ICONS.get(resource_type, "bi-link-45deg"),
                    }
                )

        out.append(
            {
                "doi": doi,
                "authors": authors,
                "title": pub["title"],
                "journal": pub.get("publisher", ""),
                "year": pub.get("year", ""),
                "type": pub_type,
                "highlight": bool(pub.get("highlight")),
                "resources": resources,
            }
        )

    out.sort(key=lambda p: p["year"], reverse=True)

    return out


def main() -> int:
    data = fetch_lab_yaml()
    publications = data["publications"]
    out = transform(publications)

    target = Path("_data/publications.yml")
    target.parent.mkdir(exist_ok=True)
    target.write_text(
        "# Generated by sync_publications.py from rendeirolab.github.io\n"
        "# content/publications.yaml. Do not edit by hand.\n"
        + yaml.safe_dump(out, sort_keys=False, allow_unicode=True, default_flow_style=False)
    )

    counts = {}
    for pub in out:
        counts[pub["type"]] = counts.get(pub["type"], 0) + 1
    print(f"total: {len(out)}")
    for pub_type, count in sorted(counts.items()):
        print(f"  {pub_type}: {count}")

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(1)
